<a href="https://colab.research.google.com/github/anacasicande/Modelamiento/blob/main/Tarea_3_jacobo_definitiva.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
#datos
Reflux_ratio=2.5 # L/D
flow_rate=1000 #mol/h
z1=0.06
z2=0.17
z3=0.22
z4=0.20
z5=0.35
t2=140 # farenheit
t3=150 # farenheit
t4=160 # farenheit
t5=170 # farenheit
t6=180 # farenheit
t7=190 # farenheit
t8=200 # farenheit
t9=210 # farenheit
t10=220 # farenheit
t11=230 # farenheit
#constantes para las 5 especies
a1=0.7
a2=2.21
a3=1.5
a4=0.86
a5=0.71
b1=0.003
b2=0.0195
b3=-0.016
b4=-0.0097
b5=-0.0087
y1=0.000065
y2=0.000090
y3=0.000080
y4=0.000046
y5=0.000042
a = np.array([0.7, 2.21, 1.5, 0.86, 0.71])
b = np.array([0.003, 0.0195, -0.016, -0.0097, -0.0087])
temperaturas_F = np.array([0,140, 150, 160, 170, 180, 190, 200, 210, 220, 230])
z_F = np.array([0.06, 0.17, 0.22, 0.20, 0.35])
y = np.array([0.000065, 0.000090, 0.000080, 0.000046, 0.000042])


In [7]:
temperaturas_K = [(T - 32) * 5/9 + 273.15 for T in temperaturas_F]
def calculo_k(T, a, b, y):

    K = np.zeros((len(T), len(a)))


    for i in range(1, len(T)):
        for k in range(len(a)):
            # Usamos la fórmula K_{i,k} = a_k - b_k * T_i + y_k * T_i^2
            K[i, k] = a[k] - b[k] * T[i] + y[k] * T[i]**2


    for i in range(1, len(T)):
        for k in range(len(a)):
            print(f"Etapa {i+1}, Componente {k+1}: K = {K[i, k]:.4f}")

    return K
k=calculo_k(temperaturas_K, a, b, y)


Etapa 2, Componente 1: K = 6.9148
Etapa 2, Componente 2: K = 5.7026
Etapa 2, Componente 3: K = 15.7095
Etapa 2, Componente 4: K = 9.1970
Etapa 2, Componente 5: K = 8.2699
Etapa 3, Componente 1: K = 7.1408
Etapa 3, Componente 2: K = 5.9302
Etapa 3, Componente 3: K = 16.0970
Etapa 3, Componente 4: K = 9.4226
Etapa 3, Componente 5: K = 8.4750
Etapa 4, Componente 1: K = 7.3707
Etapa 4, Componente 2: K = 6.1633
Etapa 4, Componente 3: K = 16.4894
Etapa 4, Componente 4: K = 9.6511
Etapa 4, Componente 5: K = 8.6827
Etapa 5, Componente 1: K = 7.6047
Etapa 5, Componente 2: K = 6.4020
Etapa 5, Componente 3: K = 16.8868
Etapa 5, Componente 4: K = 9.8823
Etapa 5, Componente 5: K = 8.8930
Etapa 6, Componente 1: K = 7.8427
Etapa 6, Componente 2: K = 6.6463
Etapa 6, Componente 3: K = 17.2891
Etapa 6, Componente 4: K = 10.1164
Etapa 6, Componente 5: K = 9.1059
Etapa 7, Componente 1: K = 8.0847
Etapa 7, Componente 2: K = 6.8961
Etapa 7, Componente 3: K = 17.6964
Etapa 7, Componente 4: K = 10.3534
Etapa 

In [ ]:
import numpy as np

def valores_a(k):
    L = 1250  # Ejemplo de flujo de líquido en mol/h
    V = 1750  # Ejemplo de flujo de vapor en mol/h
# Inicializamos una lista para almacenar los valores de a
    a_values = np.zeros_like(k)
# Calculamos los valores de a para cada Kij
    for i in range(k.shape[0]):  # Itera sobre las filas
       for j in range(k.shape[1]):  # Itera sobre las columnas
           if k[i, j]==0:
              a_values[i,j]=L/500

           else:
              a_values[i, j] = (L / (V * k[i, j]))
    return a_values
# Mostramos los resultados
A=valores_a(k)
print(A)



[[2.5        2.5        2.5        2.5        2.5       ]
 [0.45964332 0.57418466 0.13456777 0.22896708 0.25962697]
 [0.41710115 0.54525627 0.12531328 0.21321962 0.24131274]
 [0.37913254 0.51240008 0.11694265 0.19898755 0.2248161 ]
 [0.34531579 0.47746371 0.10935176 0.18608944 0.20991117]
 [0.31521876 0.44200849 0.10245062 0.17436913 0.196405  ]
 [0.28842549 0.40723245 0.09616124 0.16369184 0.18413222]
 [0.26455026 0.37397158 0.09041591 0.15394089 0.17295054]
 [0.2432439  0.34274746 0.08515566 0.14501497 0.16273711]
 [0.22419514 0.31383379 0.08032903 0.13682586 0.15338553]
 [0.20712939 0.2873233  0.07589096 0.12929652 0.1448033 ]]


In [ ]:
import numpy as np

# Función que convierte cada columna de la matriz en un vector separado
def transformar_matriz_en_vectores(matriz):
    # Obtener las dimensiones de la matriz
    n, m = matriz.shape

    # Crear una lista de vectores de longitud n (una por cada columna de la matriz)
    vectores = [matriz[:, j] for j in range(m)]

    return vectores

# Transformar la matriz en vectores
vectores = transformar_matriz_en_vectores(A)

# Mostrar los vectores resultantes
for i, vec in enumerate(vectores):
    print(f"Vector {i+1}: {vec}")


Vector 1: [2.5        0.45964332 0.41710115 0.37913254 0.34531579 0.31521876
 0.28842549 0.26455026 0.2432439  0.22419514 0.20712939]
Vector 2: [2.5        0.57418466 0.54525627 0.51240008 0.47746371 0.44200849
 0.40723245 0.37397158 0.34274746 0.31383379 0.2873233 ]
Vector 3: [2.5        0.13456777 0.12531328 0.11694265 0.10935176 0.10245062
 0.09616124 0.09041591 0.08515566 0.08032903 0.07589096]
Vector 4: [2.5        0.22896708 0.21321962 0.19898755 0.18608944 0.17436913
 0.16369184 0.15394089 0.14501497 0.13682586 0.12929652]
Vector 5: [2.5        0.25962697 0.24131274 0.2248161  0.20991117 0.196405
 0.18413222 0.17295054 0.16273711 0.15338553 0.1448033 ]


In [ ]:
import sympy as sp
import numpy as np

# Función para generar el sistema de ecuaciones basado en un array o lista
def generar_sistema_ecuaciones(vector):
    # Si el vector es un array de NumPy, convertirlo a lista
    if isinstance(vector, np.ndarray):
        vector = vector.tolist()

    n = len(vector)

    # Definir las incógnitas simbólicas
    x = sp.symbols(f'x1:{n+1}')

    # Crear la primera ecuación (utilizando el primer valor del vector en lugar del último)
    ecuaciones = [sp.Eq(x[0], vector[0] + 1)]

    # Generar las ecuaciones subsiguientes
    for i in range(1, n):
        # Ahora cada ecuación depende de los valores correspondientes del vector, no sólo el último
        ecuacion = sp.Eq(-vector[i] * x[i-1] + x[i], 1)
        ecuaciones.append(ecuacion)

    return ecuaciones, x
def ecuaciones_a_matriz(ecuaciones, variables):
    n = len(variables)
    A = np.zeros((n, n))
    b = np.zeros(n)

    for i, eq in enumerate(ecuaciones):
        lhs, rhs = eq.lhs, eq.rhs
        lhs = sp.collect(lhs, variables)
        b[i] = float(rhs)

        for var in variables:
            if var in lhs.free_symbols:
                A[i, variables.index(var)] = float(lhs.coeff(var))

    return A, b
def juntar_matriz_y_vector(A, b):
    # Convertir el vector b en una columna
    b_columna = b.reshape(-1, 1)
    # Concatenar la matriz A y la columna b
    matriz_extendida = np.hstack((A, b_columna))
    return matriz_extendida
def gaussian_elimination(matrix):
    matrix = [list(row) for row in matrix]
    rows = len(matrix)
    cols = len(matrix[0])

    for i in range(min(rows, cols)):
        # Pivote parcial, busca el elemento máximo en la columna i
        max_row = max(range(i, rows), key=lambda x: abs(matrix[x][i]))
        matrix[i], matrix[max_row] = matrix[max_row], matrix[i]

        if matrix[i][i] == 0:
            # La matriz es singular o casi singular
            raise ValueError("La matriz es singular.")

        # Hace ceros debajo del pivote
        for j in range(i + 1, rows):
            factor = matrix[j][i] / matrix[i][i]
            for k in range(i + 1, cols):
                matrix[j][k] -= factor * matrix[i][k]
            matrix[j][i] = 0

    return matrix


vector1 = np.array([2.5, 0.45964332, 0.41710115, 0.37913254, 0.34531579,
                    0.31521876, 0.28842549, 0.26455026, 0.2432439, 0.22419514, 0.20712939])

vector2 = np.array([2.5, 0.57418466, 0.54525627, 0.51240008, 0.47746371,
                    0.44200849, 0.40723245, 0.37397158, 0.34274746, 0.31383379, 0.2873233])

vector3 = np.array([2.5, 0.13456777, 0.12531328, 0.11694265, 0.10935176,
                    0.10245062, 0.09616124, 0.09041591, 0.08515566, 0.08032903, 0.07589096])

vector4 = np.array([2.5, 0.22896708, 0.21321962, 0.19898755, 0.18608944,
                    0.17436913, 0.16369184, 0.15394089, 0.14501497, 0.13682586, 0.12929652])

vector5 = np.array([2.5, 0.25962697, 0.24131274, 0.2248161, 0.20991117,
                    0.196405, 0.18413222, 0.17295054, 0.16273711, 0.15338553, 0.1448033])

# Generar el sistema de ecuaciones
sistema, variables = generar_sistema_ecuaciones(vector1)
sistema, variables = generar_sistema_ecuaciones(vector2)
sistema, variables = generar_sistema_ecuaciones(vector3)
sistema, variables = generar_sistema_ecuaciones(vector4)
sistema, variables = generar_sistema_ecuaciones(vector5)

vectores = [vector1, vector2, vector3, vector4, vector5]

for idx, vector in enumerate(vectores, start=1):
    # Generar el sistema de ecuaciones
    sistema, variables = generar_sistema_ecuaciones(vector)

    # Convertir el sistema de ecuaciones en una matriz de coeficientes y un vector de constantes
    A, b = ecuaciones_a_matriz(sistema, variables)
    matriz_extendida = juntar_matriz_y_vector(A, b)



    # Mostrar la matriz de coeficientes y el vector de constantes
    print(f"\nMatriz de coeficientes A para el Vector {idx}:")
    print(A)

    print(f"\nVector de constantes b para el Vector {idx}:")
    print(b)
    print(f"\nMatriz extendida [A | b] para el Vector {idx}:")
    print(matriz_extendida)
    # Mostrar el sistema de ecuaciones
    print(f"\nSistema de ecuaciones para el Vector {idx}:")
    for eq in sistema:
        sp.pprint(eq)
    # Mostrar el resultado de la eliminación gaussiana
    print(f"\nMatriz extendida tras la eliminación gaussiana para el Vector {idx}:")
    for fila in resultado:
        sp.pprint(fila)


    # Aplicar eliminación gaussiana
    resultado = gaussian_elimination(matriz_extendida)


Matriz de coeficientes A para el Vector 1:
[[ 1.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.        ]
 [-0.45964332  1.          0.          0.          0.          0.
   0.          0.          0.          0.          0.        ]
 [ 0.         -0.41710115  1.          0.          0.          0.
   0.          0.          0.          0.          0.        ]
 [ 0.          0.         -0.37913254  1.          0.          0.
   0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.         -0.34531579  1.          0.
   0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.         -0.31521876  1.
   0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.         -0.28842549
   1.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.    

In [ ]:
import sympy as sp
import numpy as np

# Función para realizar la sustitución hacia atrás
def back_substitution(matrix):
    rows, cols = matrix.shape
    x = np.zeros(rows)

    # Realizar sustitución hacia atrás
    for i in range(rows - 1, -1, -1):
        x[i] = matrix[i, -1] / matrix[i, i]
        for j in range(i - 1, -1, -1):
            matrix[j, -1] -= matrix[j, i] * x[i]

    return x



for idx, vector in enumerate(vectores, start=1):
    # Generar el sistema de ecuaciones
    sistema, variables = generar_sistema_ecuaciones(vector)

    # Convertir el sistema de ecuaciones en una matriz de coeficientes y un vector de constantes
    A, b = ecuaciones_a_matriz(sistema, variables)
    matriz_extendida = juntar_matriz_y_vector(A, b)

    # Aplicar eliminación gaussiana
    resultado = gaussian_elimination(matriz_extendida)



    # Obtener los valores de x_ij con sustitución hacia atrás
    resultado_np = np.array(resultado)
    valores_x = back_substitution(resultado_np)

    # Mostrar los valores de las incógnitas x_ij
    print(f"\nValores de las incógnitas x_ij para el Vector {idx}:")
    for i, valor in enumerate(valores_x, start=1):
        print(f"x{i} = {valor}")



Valores de las incógnitas x_ij para el Vector 1:
x1 = 3.5
x2 = 2.60875162
x3 = 2.088113300766363
x4 = 1.7916716995273352
x5 = 1.6186925283429243
x6 = 1.5102422516055214
x7 = 1.435592361438026
x8 = 1.3797863324724438
x9 = 1.3356246086772938
x10 = 1.299440546129851
x11 = 1.269152327661143

Valores de las incógnitas x_ij para el Vector 2:
x1 = 3.5
x2 = 3.00964631
x3 = 2.6410285210098636
x4 = 2.353263225447736
x5 = 2.1235977902288425
x6 = 1.9386482526263875
x7 = 1.7894804776052626
x8 = 1.6692148415891948
x9 = 1.572119147148999
x10 = 1.493384110281338
x11 = 1.429084050733598

Valores de las incógnitas x_ij para el Vector 3:
x1 = 3.5
x2 = 1.470987195
x3 = 1.1843342302434496
x4 = 1.1384991833703793
x5 = 1.1244968894601137
x6 = 1.1152054035132601
x7 = 1.1072395344565353
x8 = 1.100112070095864
x9 = 1.0936807694029795
x10 = 1.087854315335795
x11 = 1.0825583083309762

Valores de las incógnitas x_ij para el Vector 4:
x1 = 3.5
x2 = 1.80138478
x3 = 1.3840905782653836
x4 = 1.2754167931471119
x5 = 1.

In [ ]:
#flujo molar     v=V*Y     d=D*X
# xi = v/d
#xi= V*Y/D*X=1750*Y/1250*X
#k=X/Y

